apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: monitor-etc-changes
spec:
  kprobes:
    - call: "sys_openat"
      syscall: true
      args:
        - index: 1
          type: "string"
        - index: 2
          type: "int"
      selectors:
        - matchArgs:
            - index: 1
              operator: "Prefix"
              values:
                - "/etc/"
                - "/var/lib/systemd/"
            - index: 2
              operator: "Mask"
              values:
                - "0x1"
                - "0x2"
                - "0x40"
